FROM docker.io/library/ubuntu:latest
ADD https://proton.me/download/export-tool/proton-mail-export-cli-linux_x86_64.tar.gz /tmp/proton-mail-export-cli-linux_x86_64.tar.gz
RUN <<EOF
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates
DEBIAN_FRONTEND=noninteractive apt-get clean
tar xzf /tmp/proton-mail-export-cli-linux_x86_64.tar.gz -C /opt
rm -f /tmp/proton-mail-export-cli-linux_x86_64.tar.gz
EOF
ENTRYPOINT /opt/proton-mail-export-cli
