FROM docker.io/library/ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
ARG deblink=https://software.sonicwall.com/NetExtender/NetExtender-linux-amd64-10.3.0-21.deb
ADD $deblink /tmp/
RUN <<EOF
apt-get install -y /tmp/*.deb
EOF
ENTRYPOINT /bin/bash
