FROM docker.io/library/ubuntu:latest
ARG deblink=https://software.sonicwall.com/NetExtender/NetExtender-linux-amd64-10.3.0-21.deb
ADD $deblink /tmp/NetExtender.deb
RUN <<EOF
DEBIAN_FRONTEND=noninteractive apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y libglib2.0-0t64 libwebkit2gtk-4.1-0
# DEBIAN_FRONTEND=noninteractive apt-get install -y systemd
DEBIAN_FRONTEND=noninteractive apt-get install -y /tmp/NetExtender.deb
DEBIAN_FRONTEND=noninteractive apt-get clean
rm -f /tmp/NetExtender.deb
EOF
# ENTRYPOINT /lib/systemd/systemd
ENTRYPOINT /bin/bash
